//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADONETExample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auto
    {
        public int Id { get; set; }
        public string mark_auto { get; set; }
        public string color_auto { get; set; }
        public string date { get; set; }
        public string price { get; set; }
        public string type_auto { get; set; }
        public string engine { get; set; }
        public string isKazakstan { get; set; }
        public string decs { get; set; }
    }
}
